//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueScoreManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RescueScoreManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AgeMax.
        /// </summary>
        internal static string AgeMax_XMI {
            get {
                return ResourceManager.GetString("AgeMax_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AgeMin.
        /// </summary>
        internal static string AgeMin_XMI {
            get {
                return ResourceManager.GetString("AgeMin_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun forfait.
        /// </summary>
        internal static string AllTeamsActive {
            get {
                return ResourceManager.GetString("AllTeamsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les engagements forfaits.
        /// </summary>
        internal static string AllTeamsForfeited {
            get {
                return ResourceManager.GetString("AllTeamsForfeited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes les engagements sont forfaits pour.
        /// </summary>
        internal static string AllTeamsForfeitedFor {
            get {
                return ResourceManager.GetString("AllTeamsForfeitedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les engagements sont forfaits pour athlète.
        /// </summary>
        internal static string AllTeamsForfeitedForAthlete {
            get {
                return ResourceManager.GetString("AllTeamsForfeitedForAthlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation des forfaits pour tous les engagements.
        /// </summary>
        internal static string AllTeamsRestoredFor {
            get {
                return ResourceManager.GetString("AllTeamsRestoredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Athlete.
        /// </summary>
        internal static string Athlete_XMI {
            get {
                return ResourceManager.GetString("Athlete_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Athlètes.
        /// </summary>
        internal static string Athletes {
            get {
                return ResourceManager.GetString("Athletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Athletes_XMI.
        /// </summary>
        internal static string Athletes_XMI {
            get {
                return ResourceManager.GetString("Athletes_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Availabilities.
        /// </summary>
        internal static string Availabilities_XMI {
            get {
                return ResourceManager.GetString("Availabilities_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Côtier.
        /// </summary>
        internal static string Beach {
            get {
                return ResourceManager.GetString("Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BeachType.
        /// </summary>
        internal static string BeachType_XMI {
            get {
                return ResourceManager.GetString("BeachType_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de début.
        /// </summary>
        internal static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BeginDate.
        /// </summary>
        internal static string BeginDate_XMI {
            get {
                return ResourceManager.GetString("BeginDate_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BirthYear.
        /// </summary>
        internal static string BirthYear_XMI {
            get {
                return ResourceManager.GetString("BirthYear_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CapUrl.
        /// </summary>
        internal static string CapUrl_XMI {
            get {
                return ResourceManager.GetString("CapUrl_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categories.
        /// </summary>
        internal static string Categories_XMI {
            get {
                return ResourceManager.GetString("Categories_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        internal static string Category_XMI {
            get {
                return ResourceManager.GetString("Category_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifications enregistrées.
        /// </summary>
        internal static string ChangesSavedSuccessfully {
            get {
                return ResourceManager.GetString("ChangesSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ChronoType.
        /// </summary>
        internal static string ChronoType_XMI {
            get {
                return ResourceManager.GetString("ChronoType_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulez.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Club.
        /// </summary>
        internal static string Club_XMI {
            get {
                return ResourceManager.GetString("Club_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clubs.
        /// </summary>
        internal static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clubs.
        /// </summary>
        internal static string Clubs_XMI {
            get {
                return ResourceManager.GetString("Clubs_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste Clubs.
        /// </summary>
        internal static string ClubsList {
            get {
                return ResourceManager.GetString("ClubsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Competition.
        /// </summary>
        internal static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Competition.
        /// </summary>
        internal static string Competition_XMI {
            get {
                return ResourceManager.GetString("Competition_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        internal static string CompetitionLevel_XMI {
            get {
                return ResourceManager.GetString("CompetitionLevel_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compétition chargée.
        /// </summary>
        internal static string CompetitionLoadedInfo {
            get {
                return ResourceManager.GetString("CompetitionLoadedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecté.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Données chargées avec succès.
        /// </summary>
        internal static string DataLoadedSuccess {
            get {
                return ResourceManager.GetString("DataLoadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des données.
        /// </summary>
        internal static string DataLoadingInfo {
            get {
                return ResourceManager.GetString("DataLoadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string Description_XMI {
            get {
                return ResourceManager.GetString("Description_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discipline.
        /// </summary>
        internal static string Discipline_XMI {
            get {
                return ResourceManager.GetString("Discipline_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disqualification.
        /// </summary>
        internal static string Disqualification {
            get {
                return ResourceManager.GetString("Disqualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distance.
        /// </summary>
        internal static string Distance_XMI {
            get {
                return ResourceManager.GetString("Distance_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EndDate.
        /// </summary>
        internal static string EndDate_XMI {
            get {
                return ResourceManager.GetString("EndDate_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin du chargement.
        /// </summary>
        internal static string EndLoadingInfo {
            get {
                return ResourceManager.GetString("EndLoadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EntryLimitDate.
        /// </summary>
        internal static string EntryLimitDate_XMI {
            get {
                return ResourceManager.GetString("EntryLimitDate_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EntryTime.
        /// </summary>
        internal static string EntryTime_XMI {
            get {
                return ResourceManager.GetString("EntryTime_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du forfait de tous les engagements pour athlètes.
        /// </summary>
        internal static string ErrorForfeitingAllTeams {
            get {
                return ResourceManager.GetString("ErrorForfeitingAllTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur Chargement Données.
        /// </summary>
        internal static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;annulation de tous les forfaits.
        /// </summary>
        internal static string ErrorRestoringAllTeams {
            get {
                return ResourceManager.GetString("ErrorRestoringAllTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;enregistrement des modifications.
        /// </summary>
        internal static string ErrorSavingChanges {
            get {
                return ResourceManager.GetString("ErrorSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du changement de forfait pour l&apos;engagement.
        /// </summary>
        internal static string ErrorTogglingTeamForfeitForTeam {
            get {
                return ResourceManager.GetString("ErrorTogglingTeamForfeitForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur mise à jour forfait pour engagement.
        /// </summary>
        internal static string ErrorUpdatingTeamForfeitStatus {
            get {
                return ResourceManager.GetString("ErrorUpdatingTeamForfeitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création du fichier.
        /// </summary>
        internal static string FileCreationInfo {
            get {
                return ResourceManager.GetString("FileCreationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succès chargement fichier.
        /// </summary>
        internal static string FileLoadedSuccess {
            get {
                return ResourceManager.GetString("FileLoadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur Chargement Fichier ffss.
        /// </summary>
        internal static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier ouvert !.
        /// </summary>
        internal static string FileOpenInfo {
            get {
                return ResourceManager.GetString("FileOpenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FirstName.
        /// </summary>
        internal static string FirstName_XMI {
            get {
                return ResourceManager.GetString("FirstName_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forfait Global.
        /// </summary>
        internal static string ForfeitAll {
            get {
                return ResourceManager.GetString("ForfeitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forfaits.
        /// </summary>
        internal static string Forfeits {
            get {
                return ResourceManager.GetString("Forfeits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forfait de l&apos;athlète pour tous les engagements.
        /// </summary>
        internal static string ForfeitThisAthleteFromAllTheirTeams {
            get {
                return ResourceManager.GetString("ForfeitThisAthleteFromAllTheirTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gender.
        /// </summary>
        internal static string Gender_XMI {
            get {
                return ResourceManager.GetString("Gender_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juge Principal.
        /// </summary>
        internal static string HeadReferee {
            get {
                return ResourceManager.GetString("HeadReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HeadReferee.
        /// </summary>
        internal static string HeadReferee_XMI {
            get {
                return ResourceManager.GetString("HeadReferee_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acceuil.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur HTTP.
        /// </summary>
        internal static string HttpError {
            get {
                return ResourceManager.GetString("HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id.
        /// </summary>
        internal static string Id_XMI {
            get {
                return ResourceManager.GetString("Id_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IndividualTeam.
        /// </summary>
        internal static string IndividualTeam_XMI {
            get {
                return ResourceManager.GetString("IndividualTeam_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interval.
        /// </summary>
        internal static string Interval_XMI {
            get {
                return ResourceManager.GetString("Interval_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsEligibleToNationalRecord.
        /// </summary>
        internal static string IsEligibleToNationalRecord_XMI {
            get {
                return ResourceManager.GetString("IsEligibleToNationalRecord_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsForfeit.
        /// </summary>
        internal static string IsForfeit_XMI {
            get {
                return ResourceManager.GetString("IsForfeit_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsForfeitFinal.
        /// </summary>
        internal static string IsForfeitFinal_XMI {
            get {
                return ResourceManager.GetString("IsForfeitFinal_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsGuest.
        /// </summary>
        internal static string IsGuest_XMI {
            get {
                return ResourceManager.GetString("IsGuest_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsLicensee.
        /// </summary>
        internal static string IsLicensee_XMI {
            get {
                return ResourceManager.GetString("IsLicensee_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsRelay.
        /// </summary>
        internal static string IsRelay_XMI {
            get {
                return ResourceManager.GetString("IsRelay_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsValid.
        /// </summary>
        internal static string IsValid_XMI {
            get {
                return ResourceManager.GetString("IsValid_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LastName.
        /// </summary>
        internal static string LastName_XMI {
            get {
                return ResourceManager.GetString("LastName_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        internal static string Level_XMI {
            get {
                return ResourceManager.GetString("Level_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licensee.
        /// </summary>
        internal static string Licensee_XMI {
            get {
                return ResourceManager.GetString("Licensee_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LicenseeNumber.
        /// </summary>
        internal static string LicenseeNumber_XMI {
            get {
                return ResourceManager.GetString("LicenseeNumber_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licensees.
        /// </summary>
        internal static string Licensees_XMI {
            get {
                return ResourceManager.GetString("Licensees_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des Athlètes....
        /// </summary>
        internal static string LoadingAthletes {
            get {
                return ResourceManager.GetString("LoadingAthletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur récupération de l&apos;image.
        /// </summary>
        internal static string LoadingImageError {
            get {
                return ResourceManager.GetString("LoadingImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        internal static string Location_XMI {
            get {
                return ResourceManager.GetString("Location_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La connexion a échoué. Vérifiez vos identifiants..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion Réussie.
        /// </summary>
        internal static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CONNEXION.
        /// </summary>
        internal static string LoginUpper {
            get {
                return ResourceManager.GetString("LoginUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LogoUrl.
        /// </summary>
        internal static string LogoUrl_XMI {
            get {
                return ResourceManager.GetString("LogoUrl_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MaxLevel.
        /// </summary>
        internal static string MaxLevel_XMI {
            get {
                return ResourceManager.GetString("MaxLevel_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messieurs.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Procès Verbal.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mixte.
        /// </summary>
        internal static string Mixte {
            get {
                return ResourceManager.GetString("Mixte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Name_XMI {
            get {
                return ResourceManager.GetString("Name_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NameEnglish.
        /// </summary>
        internal static string NameEnglish_XMI {
            get {
                return ResourceManager.GetString("NameEnglish_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationality.
        /// </summary>
        internal static string Nationality_XMI {
            get {
                return ResourceManager.GetString("Nationality_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NationalityCode.
        /// </summary>
        internal static string NationalityCode_XMI {
            get {
                return ResourceManager.GetString("NationalityCode_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle Compétition.
        /// </summary>
        internal static string NewCompetition {
            get {
                return ResourceManager.GetString("NewCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun fichier de disqualification existant!.
        /// </summary>
        internal static string NoDisqualificationFileError {
            get {
                return ResourceManager.GetString("NoDisqualificationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de connexion internet.
        /// </summary>
        internal static string NoInternetConnectionError {
            get {
                return ResourceManager.GetString("NoInternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non Connecté.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun Engagement.
        /// </summary>
        internal static string NoTeams {
            get {
                return ResourceManager.GetString("NoTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number.
        /// </summary>
        internal static string Number_XMI {
            get {
                return ResourceManager.GetString("Number_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NumberByTeam.
        /// </summary>
        internal static string NumberByTeam_XMI {
            get {
                return ResourceManager.GetString("NumberByTeam_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème lors de l&apos;ouverture du fichier!.
        /// </summary>
        internal static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OrderNumber.
        /// </summary>
        internal static string OrderNumber_XMI {
            get {
                return ResourceManager.GetString("OrderNumber_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organizer.
        /// </summary>
        internal static string Organizer_XMI {
            get {
                return ResourceManager.GetString("Organizer_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eau Plate.
        /// </summary>
        internal static string Pool {
            get {
                return ResourceManager.GetString("Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PriceByAthlete.
        /// </summary>
        internal static string PriceByAthlete_XMI {
            get {
                return ResourceManager.GetString("PriceByAthlete_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PriceByClub.
        /// </summary>
        internal static string PriceByClub_XMI {
            get {
                return ResourceManager.GetString("PriceByClub_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PriceByEntry.
        /// </summary>
        internal static string PriceByEntry_XMI {
            get {
                return ResourceManager.GetString("PriceByEntry_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès Rapide.
        /// </summary>
        internal static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Race.
        /// </summary>
        internal static string Race_XMI {
            get {
                return ResourceManager.GetString("Race_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Epreuves.
        /// </summary>
        internal static string Races {
            get {
                return ResourceManager.GetString("Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Races.
        /// </summary>
        internal static string Races_XMI {
            get {
                return ResourceManager.GetString("Races_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classements.
        /// </summary>
        internal static string Rankings {
            get {
                return ResourceManager.GetString("Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prêt.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Referee.
        /// </summary>
        internal static string Referee_XMI {
            get {
                return ResourceManager.GetString("Referee_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juges.
        /// </summary>
        internal static string Referees {
            get {
                return ResourceManager.GetString("Referees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rafraichir liste des compétitions.
        /// </summary>
        internal static string RefreshCompetitionList {
            get {
                return ResourceManager.GetString("RefreshCompetitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RelayTeam.
        /// </summary>
        internal static string RelayTeam_XMI {
            get {
                return ResourceManager.GetString("RelayTeam_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restaurez tout.
        /// </summary>
        internal static string RestoreAll {
            get {
                return ResourceManager.GetString("RestoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restaure tous les engagements.
        /// </summary>
        internal static string RestoreThisAthleteToAllTheirTeams {
            get {
                return ResourceManager.GetString("RestoreThisAthleteToAllTheirTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la récupération.
        /// </summary>
        internal static string RetrieveFailedError {
            get {
                return ResourceManager.GetString("RetrieveFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Root.
        /// </summary>
        internal static string Root_XMI {
            get {
                return ResourceManager.GetString("Root_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la sauvegarde des données d&apos;authentification.
        /// </summary>
        internal static string SaveTokenError {
            get {
                return ResourceManager.GetString("SaveTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde ....
        /// </summary>
        internal static string SavingChanges {
            get {
                return ResourceManager.GetString("SavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche par athlète.
        /// </summary>
        internal static string SearchByAthleteName {
            get {
                return ResourceManager.GetString("SearchByAthleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche par club.
        /// </summary>
        internal static string SearchByClubName {
            get {
                return ResourceManager.GetString("SearchByClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection Compétition.
        /// </summary>
        internal static string SelectCompetition {
            get {
                return ResourceManager.GetString("SelectCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speciality.
        /// </summary>
        internal static string Speciality_XMI {
            get {
                return ResourceManager.GetString("Speciality_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StartList.
        /// </summary>
        internal static string StartList {
            get {
                return ResourceManager.GetString("StartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        internal static string Status_XMI {
            get {
                return ResourceManager.GetString("Status_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StatusLabel.
        /// </summary>
        internal static string StatusLabel_XMI {
            get {
                return ResourceManager.GetString("StatusLabel_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SwimType.
        /// </summary>
        internal static string SwimType_XMI {
            get {
                return ResourceManager.GetString("SwimType_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team.
        /// </summary>
        internal static string Team_XMI {
            get {
                return ResourceManager.GetString("Team_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Engagements.
        /// </summary>
        internal static string TeamDetails {
            get {
                return ResourceManager.GetString("TeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forfait pour l&apos;engagement.
        /// </summary>
        internal static string TeamForfeitToggledFor {
            get {
                return ResourceManager.GetString("TeamForfeitToggledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teams.
        /// </summary>
        internal static string Teams_XMI {
            get {
                return ResourceManager.GetString("Teams_XMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à engagements forfaits.
        /// </summary>
        internal static string TeamsForfeited {
            get {
                return ResourceManager.GetString("TeamsForfeited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changement de statut du forfait.
        /// </summary>
        internal static string ToggleTeamForfeitStatus {
            get {
                return ResourceManager.GetString("ToggleTeamForfeitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de récupérer le jeton..
        /// </summary>
        internal static string TokenError {
            get {
                return ResourceManager.GetString("TokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur Inattendue.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inconnu.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur Inconnu.
        /// </summary>
        internal static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dames.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
    }
}
