name: Build RescueScoreManager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  version: "1.0.${{ github.run_number }}"
  DOTNET_VERSION: '8.x'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version="${{ env.version }}"

      - name: Run tests
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ${{github.workspace}}/.build/coverage --logger trx --results-directory ${{github.workspace}}/.build/test-results

      - name: Generate Code Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.7
        with:
          reports: ${{github.workspace}}/.build/coverage/**/coverage.cobertura.xml
          targetdir: ${{github.workspace}}/.build/coveragereport/
          reporttypes: Html;MarkdownSummaryGithub
          title: 'Code Coverage Report'

      - name: Write PR Number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          New-Item -Type File -Value "${{ github.event.number }}" -Force -Path "${{github.workspace}}/.build/coveragereport/PullRequestNumber"

      - name: Upload Code Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CodeCoverage
          path: ${{github.workspace}}/.build/coveragereport/
          if-no-files-found: error

      - name: Publish application
        if: ${{ github.event_name != 'pull_request' }}
        run: dotnet publish --configuration Release --no-build -p:Version="${{ env.version }}" -p:PublishDir=${{github.workspace}}/.build/publish

      - name: Upload build artifacts
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{github.workspace}}/.build/publish
          retention-days: 30

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security scan
        uses: securecodewarrior/github-action-add-sarif@v1
        with:
          sarif-file: 'security-scan-results.sarif'

  auto-merge:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Auto-merge Dependabot PRs
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          use-github-auto-merge: true
          merge-method: squash